
AIRPORTS = {

# ================= INDIA =================

"Agartala (IXA)": "IXA",
"Agatti (AGX)": "AGX",
"Ahmedabad (AMD)": "AMD",
"Aizawl (AJL)": "AJL",
"Amritsar (ATQ)": "ATQ",
"Aurangabad (IXU)": "IXU",
"Bagdogra (IXB)": "IXB",
"Belagavi (IXG)": "IXG",
"Bengaluru (BLR)": "BLR",
"Bhopal (BHO)": "BHO",
"Bhubaneswar (BBI)": "BBI",
"Chandigarh (IXC)": "IXC",
"Chennai (MAA)": "MAA",
"Coimbatore (CJB)": "CJB",
"Dehradun (DED)": "DED",
"Delhi (DEL)": "DEL",
"Dibrugarh (DIB)": "DIB",
"Dimapur (DMU)": "DMU",
"Durgapur (RDP)": "RDP",
"Gaya (GAY)": "GAY",
"Goa Dabolim (GOI)": "GOI",
"Goa Mopa (GOX)": "GOX",
"Gorakhpur (GOP)": "GOP",
"Guwahati (GAU)": "GAU",
"Gwalior (GWL)": "GWL",
"Hubli (HBX)": "HBX",
"Hyderabad (HYD)": "HYD",
"Imphal (IMF)": "IMF",
"Indore (IDR)": "IDR",
"Jabalpur (JLR)": "JLR",
"Jaipur (JAI)": "JAI",
"Jammu (IXJ)": "IXJ",
"Jamnagar (JGA)": "JGA",
"Jodhpur (JDH)": "JDH",
"Kannur (CNN)": "CNN",
"Kochi (COK)": "COK",
"Kolhapur (KLH)": "KLH",
"Kolkata (CCU)": "CCU",
"Kozhikode (CCJ)": "CCJ",
"Leh (IXL)": "IXL",
"Lucknow (LKO)": "LKO",
"Madurai (IXM)": "IXM",
"Mangaluru (IXE)": "IXE",
"Mumbai (BOM)": "BOM",
"Mysuru (MYQ)": "MYQ",
"Nagpur (NAG)": "NAG",
"Nashik (ISK)": "ISK",
"Patna (PAT)": "PAT",
"Port Blair (IXZ)": "IXZ",
"Pune (PNQ)": "PNQ",
"Raipur (RPR)": "RPR",
"Rajkot (HSR)": "HSR",
"Ranchi (IXR)": "IXR",
"Shillong (SHL)": "SHL",
"Silchar (IXS)": "IXS",
"Srinagar (SXR)": "SXR",
"Surat (STV)": "STV",
"Tiruchirappalli (TRZ)": "TRZ",
"Tirupati (TIR)": "TIR",
"Thiruvananthapuram (TRV)": "TRV",
"Udaipur (UDR)": "UDR",
"Vadodara (BDQ)": "BDQ",
"Varanasi (VNS)": "VNS",
"Vijayawada (VGA)": "VGA",
"Visakhapatnam (VTZ)": "VTZ",

# --------ABROAD----------
# ================= ASIA & MIDDLE EAST =================

"Abu Dhabi (AUH)": "AUH",
"Almaty (ALA)": "ALA",
"Amman (AMM)": "AMM",
"Bahrain (BAH)": "BAH",
"Baku (GYD)": "GYD",
"Bandar Seri Begawan (BWN)": "BWN",
"Bangkok Suvarnabhumi (BKK)": "BKK",
"Bangkok Don Mueang (DMK)": "DMK",
"Beijing Capital (PEK)": "PEK",
"Beijing Daxing (PKX)": "PKX",
"Bishkek (FRU)": "FRU",
"Busan (PUS)": "PUS",
"Cebu (CEB)": "CEB",
"Chengdu Tianfu (TFU)": "TFU",
"Chiang Mai (CNX)": "CNX",
"Colombo (CMB)": "CMB",
"Dhaka (DAC)": "DAC",
"Doha (DOH)": "DOH",
"Dubai (DXB)": "DXB",
"Dubai Al Maktoum (DWC)": "DWC",
"Fukuoka (FUK)": "FUK",
"Guangzhou (CAN)": "CAN",
"Hanoi (HAN)": "HAN",
"Ho Chi Minh City (SGN)": "SGN",
"Hong Kong (HKG)": "HKG",
"Islamabad (ISB)": "ISB",
"Jakarta (CGK)": "CGK",
"Jeddah (JED)": "JED",
"Karachi (KHI)": "KHI",
"Kathmandu (KTM)": "KTM",
"Kuala Lumpur (KUL)": "KUL",
"Kuwait City (KWI)": "KWI",
"Lahore (LHE)": "LHE",
"Male (MLE)": "MLE",
"Manila (MNL)": "MNL",
"Muscat (MCT)": "MCT",
"Nagoya (NGO)": "NGO",
"Osaka Kansai (KIX)": "KIX",
"Phnom Penh (PNH)": "PNH",
"Phuket (HKT)": "HKT",
"Riyadh (RUH)": "RUH",
"Seoul Incheon (ICN)": "ICN",
"Shanghai Pudong (PVG)": "PVG",
"Shanghai Hongqiao (SHA)": "SHA",
"Shenzhen (SZX)": "SZX",
"Singapore Changi (SIN)": "SIN",
"Taipei Taoyuan (TPE)": "TPE",
"Tel Aviv (TLV)": "TLV",
"Tokyo Haneda (HND)": "HND",
"Tokyo Narita (NRT)": "NRT",
"Ulaanbaatar (UBN)": "UBN",
"Vientiane (VTE)": "VTE",
"Yangon (RGN)": "RGN",
"Yogyakarta (YIA)": "YIA",
"Denpasar Bali (DPS)": "DPS",
# ================= EUROPE =================

"Amsterdam Schiphol (AMS)": "AMS",
"Athens (ATH)": "ATH",
"Barcelona (BCN)": "BCN",
"Belgrade (BEG)": "BEG",
"Berlin Brandenburg (BER)": "BER",
"Birmingham (BHX)": "BHX",
"Bologna (BLQ)": "BLQ",
"Brussels (BRU)": "BRU",
"Budapest (BUD)": "BUD",
"Bucharest (OTP)": "OTP",
"Cologne Bonn (CGN)": "CGN",
"Copenhagen (CPH)": "CPH",
"Dublin (DUB)": "DUB",
"Düsseldorf (DUS)": "DUS",
"Edinburgh (EDI)": "EDI",
"Frankfurt (FRA)": "FRA",
"Geneva (GVA)": "GVA",
"Glasgow (GLA)": "GLA",
"Hamburg (HAM)": "HAM",
"Helsinki (HEL)": "HEL",
"Istanbul (IST)": "IST",
"Istanbul Sabiha Gökçen (SAW)": "SAW",
"Kraków (KRK)": "KRK",
"Lisbon (LIS)": "LIS",
"London City (LCY)": "LCY",
"London Gatwick (LGW)": "LGW",
"London Heathrow (LHR)": "LHR",
"London Luton (LTN)": "LTN",
"London Stansted (STN)": "STN",
"Luxembourg (LUX)": "LUX",
"Lyon (LYS)": "LYS",
"Madrid (MAD)": "MAD",
"Malaga (AGP)": "AGP",
"Manchester (MAN)": "MAN",
"Milan Linate (LIN)": "LIN",
"Milan Malpensa (MXP)": "MXP",
"Munich (MUC)": "MUC",
"Naples (NAP)": "NAP",
"Nice (NCE)": "NCE",
"Oslo (OSL)": "OSL",
"Palma de Mallorca (PMI)": "PMI",
"Paris Charles de Gaulle (CDG)": "CDG",
"Paris Orly (ORY)": "ORY",
"Porto (OPO)": "OPO",
"Prague (PRG)": "PRG",
"Reykjavik Keflavik (KEF)": "KEF",
"Rome Fiumicino (FCO)": "FCO",
"Stockholm Arlanda (ARN)": "ARN",
"Stuttgart (STR)": "STR",
"Venice Marco Polo (VCE)": "VCE",
"Vienna (VIE)": "VIE",
"Warsaw Chopin (WAW)": "WAW",
"Zurich (ZRH)": "ZRH",
# ================= REST OF WORLD =================

# USA
"Atlanta (ATL)": "ATL",
"Austin (AUS)": "AUS",
"Boston (BOS)": "BOS",
"Charlotte (CLT)": "CLT",
"Chicago O'Hare (ORD)": "ORD",
"Dallas/Fort Worth (DFW)": "DFW",
"Denver (DEN)": "DEN",
"Detroit (DTW)": "DTW",
"Honolulu (HNL)": "HNL",
"Houston (IAH)": "IAH",
"Las Vegas (LAS)": "LAS",
"Los Angeles (LAX)": "LAX",
"Miami (MIA)": "MIA",
"New York JFK (JFK)": "JFK",
"Newark (EWR)": "EWR",
"Orlando (MCO)": "MCO",
"Philadelphia (PHL)": "PHL",
"Phoenix (PHX)": "PHX",
"San Diego (SAN)": "SAN",
"San Francisco (SFO)": "SFO",
"Seattle (SEA)": "SEA",
"Washington Dulles (IAD)": "IAD",

# Canada
"Calgary (YYC)": "YYC",
"Edmonton (YEG)": "YEG",
"Montreal (YUL)": "YUL",
"Ottawa (YOW)": "YOW",
"Toronto Pearson (YYZ)": "YYZ",
"Vancouver (YVR)": "YVR",

# Australia
"Adelaide (ADL)": "ADL",
"Brisbane (BNE)": "BNE",
"Cairns (CNS)": "CNS",
"Melbourne (MEL)": "MEL",
"Perth (PER)": "PER",
"Sydney (SYD)": "SYD",

# New Zealand
"Auckland (AKL)": "AKL",
"Christchurch (CHC)": "CHC",
"Wellington (WLG)": "WLG",

# South Africa
"Cape Town (CPT)": "CPT",
"Durban (DUR)": "DUR",
"Johannesburg (JNB)": "JNB",

# Brazil
"Brasilia (BSB)": "BSB",
"Rio de Janeiro (GIG)": "GIG",
"Sao Paulo Guarulhos (GRU)": "GRU",

# Argentina
"Buenos Aires (EZE)": "EZE",

# Chile
"Santiago (SCL)": "SCL",

# Peru
"Lima (LIM)": "LIM",

# Mexico
"Cancun (CUN)": "CUN",
"Mexico City (MEX)": "MEX",


}